-- Migration 0002: Identity & Auth Schema
-- SportsRush 2.0 — creates all tables for the Identity & Auth domain.
--
-- Design decisions recorded here. Do not modify this file after it is applied.
-- All changes must be additive migrations starting at 0003_*.
--
-- ── Timestamp strategy ────────────────────────────────────────────────────────
-- All timestamp columns are TEXT in ISO 8601 UTC format:
--   "2025-03-15T18:00:00.000Z"
-- This matches the Timestamp branded type in packages/types/src/common.ts.
-- ISO 8601 strings are lexicographically sortable, so range queries work correctly.
-- DEFAULT values use strftime('%Y-%m-%dT%H:%M:%fZ', 'now') for the current UTC time.
-- updated_at is managed by AFTER UPDATE triggers defined at the bottom of this file.
-- Triggers fire only when the application has not already set updated_at in the UPDATE
-- statement (WHEN NEW.updated_at IS OLD.updated_at guard). Application code MAY supply
-- an explicit updated_at (e.g. data migrations, test fixtures) and the trigger will not
-- override it.
--
-- Token-lifecycle tables (user_sessions, magic_links, password_reset_tokens) do NOT have
-- updated_at or triggers. Their state changes are captured by specific columns:
-- revoked_at, used_at, last_used_at. A generic updated_at would be redundant.
--
-- ── Primary key strategy ──────────────────────────────────────────────────────
-- All tables use UUID v4 TEXT primary keys.
-- UUIDs are generated by the application using crypto.randomUUID().
-- In D1 (SQLite), there is no UUID column type — TEXT is used.
--
-- ── Email normalisation ───────────────────────────────────────────────────────
-- Two email columns are maintained on the users table:
--   email          — original case as entered by the user, displayed in the UI
--   email_normalized — lowercased + trimmed, used for all uniqueness checks and lookups
-- The UNIQUE constraint is on email_normalized only.
-- Normalisation is performed by the application before any INSERT or lookup.
-- email_normalized is always: email.trim().toLowerCase()
--
-- ── Legacy WordPress migration ────────────────────────────────────────────────
-- Users imported from the legacy WordPress installation are marked with:
--   is_legacy_migration = 1
--   legacy_wp_user_id   = <original WP user ID (integer)>
-- These users have no password_hash initially. They must complete the migration
-- flow (magic link or password reset) to set a new PBKDF2-SHA256 password.
-- legacy_migration_completed_at is set when the migration flow is finished.
-- WordPress password hashes ($P$...) are NEVER stored.
--
-- ── Token security ───────────────────────────────────────────────────────────
-- All security tokens (magic links, password reset, refresh) are stored as
-- SHA-256 hashes only. Raw token values are:
--   1. Generated by the application.
--   2. Sent to the user (email, HTTP-only cookie, etc.).
--   3. Hashed and stored in the database.
-- On verification, the received token is hashed and compared to the stored hash.
-- All token columns include expires_at (application sets the expiry) and
-- used_at (null until consumed — single-use enforcement).
--
-- ── auth_audit_log vs domain audit_events ────────────────────────────────────
-- auth_audit_log captures authentication/security events (login, logout, etc.)
-- A separate domain-level audit_events table (admin actions on domain entities)
-- will be created in a later migration when admin endpoints are implemented.
-- Both tables are append-only — rows are never updated or deleted.

PRAGMA foreign_keys = ON;

-- ─────────────────────────────────────────────────────────────────────────────
-- USERS — core identity record, one row per human user
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE users (
  id                            TEXT NOT NULL PRIMARY KEY,

  -- Email address (display + login identifier)
  email                         TEXT NOT NULL,
  email_normalized              TEXT NOT NULL UNIQUE,  -- email.trim().toLowerCase()
  email_verified_at             TEXT,                  -- ISO 8601; null until verified

  -- Authentication credential (PBKDF2-SHA256; null until password is set)
  -- Format: $pbkdf2-sha256$<iterations>$<salt_b64url>$<hash_b64url>
  -- See packages/auth/src/password.ts for hash/verify functions.
  password_hash                 TEXT,

  -- Authorization role. Hierarchy: superadmin > admin > user.
  -- Must match the Role type in packages/types/src/auth.ts.
  role                          TEXT NOT NULL DEFAULT 'user'
                                  CHECK (role IN ('user', 'admin', 'superadmin')),

  -- Account status. Suspended users cannot authenticate.
  is_active                     INTEGER NOT NULL DEFAULT 1,

  -- ── Legacy WordPress migration fields ─────────────────────────────────────
  -- is_legacy_migration = 1 for users imported from the WordPress platform.
  -- These users must complete the migration flow before full access is granted.
  is_legacy_migration           INTEGER NOT NULL DEFAULT 0,

  -- Original WordPress user ID (integer, NOT the WordPress UUID).
  -- Null for natively registered SportsRush 2.0 accounts.
  -- Read-only after import — never updated.
  legacy_wp_user_id             INTEGER,

  -- ISO 8601 timestamp; set when the user completes their first post-migration
  -- password reset or magic link login. Null until then.
  legacy_migration_completed_at TEXT,

  -- ── Timestamps ────────────────────────────────────────────────────────────
  created_at                    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at                    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

-- ─────────────────────────────────────────────────────────────────────────────
-- USER PROFILES — display information (1-to-1 with users)
-- ─────────────────────────────────────────────────────────────────────────────
-- Separated from users to keep the identity table minimal and to allow
-- profile data to be updated at a different rate/permission level.
-- A profile row must be created atomically with its users row.

CREATE TABLE user_profiles (
  user_id      TEXT NOT NULL PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  -- Display name shown on leaderboards and league rankings.
  -- Max 3 changes per 24 hours enforced at the API layer, not DB layer.
  display_name TEXT NOT NULL DEFAULT '',
  avatar_url   TEXT,
  -- IANA timezone string, e.g. 'Europe/London'. Validated by the application.
  timezone     TEXT NOT NULL DEFAULT 'UTC',
  created_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

-- ─────────────────────────────────────────────────────────────────────────────
-- USER SESSIONS — refresh token tracking
-- ─────────────────────────────────────────────────────────────────────────────
-- One row per active device/browser session.
-- Refresh tokens are stored as SHA-256 hashes. The raw token is an HTTP-only
-- cookie on web and SecureStore on mobile.
-- A session is considered valid when: revoked_at IS NULL AND expires_at > now().

CREATE TABLE user_sessions (
  id                 TEXT NOT NULL PRIMARY KEY,
  user_id            TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  -- SHA-256 hash of the refresh token.
  refresh_token_hash TEXT NOT NULL UNIQUE,
  -- Device info for session management UI.
  user_agent         TEXT,
  ip_address         TEXT,
  created_at         TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  -- Updated whenever the session is used to issue a new access token.
  last_used_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  -- ISO 8601; set by application (typically now + 30 days for persistent sessions).
  expires_at         TEXT NOT NULL,
  -- ISO 8601; set on logout or admin revocation. Null for active sessions.
  revoked_at         TEXT
);

-- ─────────────────────────────────────────────────────────────────────────────
-- MAGIC LINKS — passwordless login tokens
-- ─────────────────────────────────────────────────────────────────────────────
-- Single-use, short-lived (15 minutes) tokens sent via email.
-- token_hash is SHA-256 of the raw URL-safe token.
-- used_at is set on first use; subsequent uses are rejected.

CREATE TABLE magic_links (
  id               TEXT NOT NULL PRIMARY KEY,
  user_id          TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  -- SHA-256 hash of the raw token. The raw token is embedded in the email link.
  token_hash       TEXT NOT NULL UNIQUE,
  -- Email address the link was sent to. May differ from users.email_normalized
  -- if the user changes their email after requesting the link.
  email_normalized TEXT NOT NULL,
  created_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  -- ISO 8601; set by application (typically now + 15 minutes).
  expires_at       TEXT NOT NULL,
  -- ISO 8601; null until consumed. Once set, the link cannot be used again.
  used_at          TEXT
);

-- ─────────────────────────────────────────────────────────────────────────────
-- OAUTH ACCOUNTS — OAuth 2.0 provider linkage
-- ─────────────────────────────────────────────────────────────────────────────
-- One row per (user, provider) pair. A user may link multiple providers.
-- provider_user_id is the stable ID from the OAuth provider (not the email).
-- UNIQUE on (provider, provider_user_id) prevents duplicate account linking.

CREATE TABLE oauth_accounts (
  id               TEXT NOT NULL PRIMARY KEY,
  user_id          TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  -- OAuth provider name, e.g. 'google', 'facebook', 'apple'.
  -- No CHECK constraint — the set of providers may grow without a migration.
  -- Validated at the application layer.
  provider         TEXT NOT NULL,
  -- The user's stable ID from the provider (not the email, which can change).
  provider_user_id TEXT NOT NULL,
  -- Email from the provider. Informational only — not used for login matching.
  email            TEXT,
  created_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),

  UNIQUE (provider, provider_user_id)
);

-- ─────────────────────────────────────────────────────────────────────────────
-- PASSWORD RESET TOKENS — single-use password reset links
-- ─────────────────────────────────────────────────────────────────────────────
-- Short-lived (15 minutes), single-use tokens sent via email.
-- token_hash is SHA-256 of the raw URL-safe token.
-- used_at is set on successful password change; further attempts are rejected.

CREATE TABLE password_reset_tokens (
  id         TEXT NOT NULL PRIMARY KEY,
  user_id    TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  -- SHA-256 hash of the raw token embedded in the reset link.
  token_hash TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  -- ISO 8601; set by application (typically now + 15 minutes).
  expires_at TEXT NOT NULL,
  -- ISO 8601; null until the password change is committed.
  used_at    TEXT
);

-- ─────────────────────────────────────────────────────────────────────────────
-- AUTH AUDIT LOG — authentication and account security events
-- ─────────────────────────────────────────────────────────────────────────────
-- Append-only. Rows are NEVER updated or deleted — no updated_at column.
-- user_id is nullable for pre-authentication events (e.g. failed login by email
-- that does not match any account — user_id cannot be determined).
-- ON DELETE SET NULL preserves the audit record even if the user is deleted.
--
-- Distinct from the domain-level audit_events table (admin actions on domain
-- entities) which will be created in a later migration.
--
-- Event type reference (application-defined, not enforced by DB CHECK):
--   user.registered          — new account created (native or OAuth)
--   user.login_success       — password or magic link login succeeded
--   user.login_failure       — authentication attempt failed
--   user.logout              — explicit logout (single session)
--   user.logout_all          — all sessions revoked
--   user.token_refreshed     — refresh token exchanged for new access token
--   user.magic_link_sent     — magic link email dispatched
--   user.magic_link_used     — magic link consumed
--   user.password_reset_sent — reset email dispatched
--   user.password_changed    — password successfully changed
--   user.email_changed       — email address updated
--   user.oauth_linked        — OAuth account linked
--   user.oauth_unlinked      — OAuth account unlinked
--   user.suspended           — account suspended by admin
--   user.reactivated         — account reactivated by admin
--   user.migration_completed — legacy WordPress user completed migration

CREATE TABLE auth_audit_log (
  id         TEXT NOT NULL PRIMARY KEY,
  user_id    TEXT REFERENCES users(id) ON DELETE SET NULL,
  event_type TEXT NOT NULL,
  ip_address TEXT,
  user_agent TEXT,
  -- JSON blob for event-specific data. Schema is application-defined per event_type.
  -- Examples: { "session_id": "..." } for login events,
  --           { "provider": "google" } for OAuth events.
  metadata   TEXT,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

-- ─────────────────────────────────────────────────────────────────────────────
-- INDEXES
-- ─────────────────────────────────────────────────────────────────────────────
-- Note: UNIQUE constraints automatically create indexes on:
--   users.email_normalized, user_sessions.refresh_token_hash,
--   magic_links.token_hash, oauth_accounts.(provider, provider_user_id),
--   password_reset_tokens.token_hash
-- These are NOT duplicated below.

-- users: role lookups for admin queries; legacy import deduplication
CREATE INDEX idx_users_role
  ON users (role);

CREATE INDEX idx_users_legacy_wp_user_id
  ON users (legacy_wp_user_id)
  WHERE legacy_wp_user_id IS NOT NULL;

-- user_sessions: enumerate all sessions for a user (logout-all, session manager)
CREATE INDEX idx_user_sessions_user_id
  ON user_sessions (user_id);

-- user_sessions: cleanup job removes expired sessions
CREATE INDEX idx_user_sessions_expires_at
  ON user_sessions (expires_at);

-- magic_links: look up pending links by user; cleanup job removes expired links
CREATE INDEX idx_magic_links_user_id
  ON magic_links (user_id);

CREATE INDEX idx_magic_links_expires_at
  ON magic_links (expires_at);

-- oauth_accounts: enumerate all linked providers for a user
CREATE INDEX idx_oauth_accounts_user_id
  ON oauth_accounts (user_id);

-- password_reset_tokens: look up pending resets by user; cleanup expired
CREATE INDEX idx_password_reset_tokens_user_id
  ON password_reset_tokens (user_id);

-- auth_audit_log: user audit trail; event type queries; time-range queries
CREATE INDEX idx_auth_audit_log_user_id
  ON auth_audit_log (user_id);

CREATE INDEX idx_auth_audit_log_event_type
  ON auth_audit_log (event_type);

CREATE INDEX idx_auth_audit_log_created_at
  ON auth_audit_log (created_at);

-- ─────────────────────────────────────────────────────────────────────────────
-- TRIGGERS — automatic updated_at maintenance
-- ─────────────────────────────────────────────────────────────────────────────
-- One trigger per mutable entity table that has an updated_at column.
-- Only fires when the UPDATE statement has not already changed updated_at
-- (WHEN NEW.updated_at IS OLD.updated_at). This means:
--   1. Normal application UPDATEs that omit updated_at → trigger sets it to now.
--   2. Application UPDATEs that explicitly set updated_at → trigger does nothing
--      (the app value is preserved; useful for data migrations and test fixtures).
--   3. No infinite recursion: the trigger's own UPDATE sets updated_at to a new
--      value, so on re-entry NEW.updated_at IS NOT OLD.updated_at → WHEN is false.
--
-- Tables WITHOUT triggers (and why):
--   user_sessions     — lifecycle tracked by last_used_at and revoked_at
--   magic_links       — lifecycle tracked by used_at; rows are write-once
--   password_reset_tokens — lifecycle tracked by used_at; rows are write-once
--   auth_audit_log    — append-only; no updates ever

CREATE TRIGGER trg_users_updated_at
  AFTER UPDATE ON users
  FOR EACH ROW
  WHEN NEW.updated_at IS OLD.updated_at
BEGIN
  UPDATE users
  SET updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = NEW.id;
END;

CREATE TRIGGER trg_user_profiles_updated_at
  AFTER UPDATE ON user_profiles
  FOR EACH ROW
  WHEN NEW.updated_at IS OLD.updated_at
BEGIN
  UPDATE user_profiles
  SET updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE user_id = NEW.user_id;
END;

CREATE TRIGGER trg_oauth_accounts_updated_at
  AFTER UPDATE ON oauth_accounts
  FOR EACH ROW
  WHEN NEW.updated_at IS OLD.updated_at
BEGIN
  UPDATE oauth_accounts
  SET updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE id = NEW.id;
END;
